### ISSUE TITLE
NW.Event.stop not working for form submit by NW.Event.dispatch

### ISSUE THREAD

**Issue by pdanpdan** [dperini/nwevents#3]
The 2 lines in http://github.com/dperini/nwevents/commit/677f3d0f5f968cf9e2578d211050ca815408e88b
have disapeared in the latest version on github

Now it dowsn't work if the submit event is triggered by NW.Event.dispatch

Test case: http://gist.github.com/338528

**Comment by dperini** [comment]
I don't see it failing in the test case you have setup.
By running the gist example I get alerted twice with "CAUGHT" and the form is not submitted since you have specified a  "NW.Event.stop(e)" in the "submit" handler canceling/preventing it from firing.

Let me know how I can replicate the problem you are seeing.

Thank you.

**Comment by dperini** [comment]
OK! Found.... I was clicking the button, not on the FORM itself.
Let me have a better look at this. The example seems to be a bit convoluted ;-)

**Comment by dperini** [comment]
committed a patch for this, see if this solves your problem:

http://github.com/dperini/nwevents/commit/3e0834b5df6498adefe68d7e597d36defa9ee934

seems I had forgotten to mark form events as "propagated" in the "dispatch()" method.

**Comment by pdanpdan** [comment]
It works fine now, thank you
